// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_stats.sql

package sqlc

import (
	"context"
)

const getTeamMembersLeaderboardStats = `-- name: GetTeamMembersLeaderboardStats :many
SELECT
    m."userId",
    COALESCE(SUM(epe.points), 0)::bigint AS total_points,
    COALESCE(AVG(rr.position), 0)::double precision AS avg_position,
    COUNT(DISTINCT epe."eventId")::bigint AS events_participated
FROM "member" m
LEFT JOIN "event_points_entry" epe ON epe."userId" = m."userId"
LEFT JOIN "race_event" re ON re."eventId" = epe."eventId"
LEFT JOIN "race_result" rr ON rr."raceEventId" = re.id AND rr."userId" = m."userId" AND rr.position IS NOT NULL
WHERE m."organizationId" = $1
GROUP BY m."userId"
`

type GetTeamMembersLeaderboardStatsRow struct {
	UserId             string
	TotalPoints        int64
	AvgPosition        float64
	EventsParticipated int64
}

// Query member leaderboard stats for a team.
func (q *Queries) GetTeamMembersLeaderboardStats(ctx context.Context, organizationid string) ([]GetTeamMembersLeaderboardStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTeamMembersLeaderboardStats, organizationid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamMembersLeaderboardStatsRow
	for rows.Next() {
		var i GetTeamMembersLeaderboardStatsRow
		if err := rows.Scan(
			&i.UserId,
			&i.TotalPoints,
			&i.AvgPosition,
			&i.EventsParticipated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
