// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: teams.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const batchCountMembersAndAdmins = `-- name: BatchCountMembersAndAdmins :many
SELECT "organizationId", COUNT(*), COUNT(*) FILTER (WHERE role = $1)
FROM "member"
WHERE "organizationId" = ANY($2::text[])
GROUP BY "organizationId"
`

type BatchCountMembersAndAdminsParams struct {
	Role    string
	Column2 []string
}

type BatchCountMembersAndAdminsRow struct {
	OrganizationId string
	Count          int64
	Count_2        int64
}

func (q *Queries) BatchCountMembersAndAdmins(ctx context.Context, arg BatchCountMembersAndAdminsParams) ([]BatchCountMembersAndAdminsRow, error) {
	rows, err := q.db.QueryContext(ctx, batchCountMembersAndAdmins, arg.Role, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchCountMembersAndAdminsRow
	for rows.Next() {
		var i BatchCountMembersAndAdminsRow
		if err := rows.Scan(&i.OrganizationId, &i.Count, &i.Count_2); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkTeamOrgLink = `-- name: CheckTeamOrgLink :one
SELECT "isPrimary" FROM "teamOrganization"
WHERE "teamId" = $1 AND "organizationId" = $2
`

type CheckTeamOrgLinkParams struct {
	TeamId         string
	OrganizationId string
}

func (q *Queries) CheckTeamOrgLink(ctx context.Context, arg CheckTeamOrgLinkParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkTeamOrgLink, arg.TeamId, arg.OrganizationId)
	var isPrimary bool
	err := row.Scan(&isPrimary)
	return isPrimary, err
}

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM "member" WHERE "organizationId" = $1 AND role = $2
`

type CountAdminsParams struct {
	OrganizationId string
	Role           string
}

func (q *Queries) CountAdmins(ctx context.Context, arg CountAdminsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins, arg.OrganizationId, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMembersAndAdmins = `-- name: CountMembersAndAdmins :one

SELECT COUNT(*), COUNT(*) FILTER (WHERE role = $2)
FROM "member" WHERE "organizationId" = $1
`

type CountMembersAndAdminsParams struct {
	OrganizationId string
	Role           string
}

type CountMembersAndAdminsRow struct {
	Count   int64
	Count_2 int64
}

// Member / Roster queries for Organization (`member` table)
func (q *Queries) CountMembersAndAdmins(ctx context.Context, arg CountMembersAndAdminsParams) (CountMembersAndAdminsRow, error) {
	row := q.db.QueryRowContext(ctx, countMembersAndAdmins, arg.OrganizationId, arg.Role)
	var i CountMembersAndAdminsRow
	err := row.Scan(&i.Count, &i.Count_2)
	return i, err
}

const countRosterForTeam = `-- name: CountRosterForTeam :one
SELECT COUNT(*) FROM "teamMember" WHERE "teamId" = $1
`

func (q *Queries) CountRosterForTeam(ctx context.Context, teamid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRosterForTeam, teamid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamMembers = `-- name: CountTeamMembers :one
SELECT COUNT(*) FROM "member" m JOIN "user" u ON u.id = m."userId"
WHERE m."organizationId" = $1
`

func (q *Queries) CountTeamMembers(ctx context.Context, organizationid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTeamMembers, organizationid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamMembersBySearch = `-- name: CountTeamMembersBySearch :one
SELECT COUNT(*) FROM "member" m JOIN "user" u ON u.id = m."userId"
WHERE m."organizationId" = $1
  AND (u.name ILIKE '%' || $2::text || '%' OR u."vrchatUsername" ILIKE '%' || $2::text || '%' OR u.slug ILIKE '%' || $2::text || '%')
`

type CountTeamMembersBySearchParams struct {
	OrganizationId string
	Column2        string
}

func (q *Queries) CountTeamMembersBySearch(ctx context.Context, arg CountTeamMembersBySearchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTeamMembersBySearch, arg.OrganizationId, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeams = `-- name: CountTeams :one

SELECT COUNT(*) FROM "team" WHERE status = 'APPROVED'
`

// Team listing and CRUD
func (q *Queries) CountTeams(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTeams)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamsBySearch = `-- name: CountTeamsBySearch :one
SELECT COUNT(*) FROM "team"
WHERE status = 'APPROVED' AND (name ILIKE '%' || $1::text || '%' OR slug ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountTeamsBySearch(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTeamsBySearch, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO "organization" (id, name, slug, logo, description, "orgType", status, "discordInvite", "vrchatGroupId", "submittedByUserId", "createdAt", "updatedAt")
VALUES (gen_random_uuid()::text, $1, $2, $3, $4, $5, $6, $7, $8, $9, CURRENT_TIMESTAMP, $10) RETURNING id
`

type CreateOrgParams struct {
	Name              string
	Slug              string
	Logo              sql.NullString
	Description       sql.NullString
	OrgType           sql.NullString
	Status            sql.NullString
	DiscordInvite     sql.NullString
	VrchatGroupId     sql.NullString
	SubmittedByUserId sql.NullString
	UpdatedAt         sql.NullTime
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createOrg,
		arg.Name,
		arg.Slug,
		arg.Logo,
		arg.Description,
		arg.OrgType,
		arg.Status,
		arg.DiscordInvite,
		arg.VrchatGroupId,
		arg.SubmittedByUserId,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createOrgWithID = `-- name: CreateOrgWithID :one
INSERT INTO "organization" (id, name, slug, logo, description, "orgType", status, "discordInvite", "vrchatGroupId", "submittedByUserId", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, CURRENT_TIMESTAMP, $11) RETURNING id
`

type CreateOrgWithIDParams struct {
	ID                string
	Name              string
	Slug              string
	Logo              sql.NullString
	Description       sql.NullString
	OrgType           sql.NullString
	Status            sql.NullString
	DiscordInvite     sql.NullString
	VrchatGroupId     sql.NullString
	SubmittedByUserId sql.NullString
	UpdatedAt         sql.NullTime
}

func (q *Queries) CreateOrgWithID(ctx context.Context, arg CreateOrgWithIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createOrgWithID,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Logo,
		arg.Description,
		arg.OrgType,
		arg.Status,
		arg.DiscordInvite,
		arg.VrchatGroupId,
		arg.SubmittedByUserId,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO "team" (id, name, slug, logo, description, status, "submittedByUserId", "createdAt", "updatedAt")
VALUES (gen_random_uuid()::text, $1, $2, $3, $4, $5, $6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) RETURNING id
`

type CreateTeamParams struct {
	Name              string
	Slug              string
	Logo              sql.NullString
	Description       sql.NullString
	Status            string
	SubmittedByUserId sql.NullString
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createTeam,
		arg.Name,
		arg.Slug,
		arg.Logo,
		arg.Description,
		arg.Status,
		arg.SubmittedByUserId,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM "member" WHERE "organizationId" = $1 AND "userId" = $2
`

type DeleteMemberParams struct {
	OrganizationId string
	UserId         string
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteMember, arg.OrganizationId, arg.UserId)
	return err
}

const deleteTeamMemberRow = `-- name: DeleteTeamMemberRow :exec
DELETE FROM "teamMember" WHERE "teamId" = $1 AND "userId" = $2
`

type DeleteTeamMemberRowParams struct {
	TeamId string
	UserId string
}

func (q *Queries) DeleteTeamMemberRow(ctx context.Context, arg DeleteTeamMemberRowParams) error {
	_, err := q.db.ExecContext(ctx, deleteTeamMemberRow, arg.TeamId, arg.UserId)
	return err
}

const deleteTeamOrganization = `-- name: DeleteTeamOrganization :exec
DELETE FROM "teamOrganization"
WHERE "teamId" = $1 AND "organizationId" = $2
`

type DeleteTeamOrganizationParams struct {
	TeamId         string
	OrganizationId string
}

func (q *Queries) DeleteTeamOrganization(ctx context.Context, arg DeleteTeamOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, deleteTeamOrganization, arg.TeamId, arg.OrganizationId)
	return err
}

const deleteTeamOrganizationsForTeam = `-- name: DeleteTeamOrganizationsForTeam :exec
DELETE FROM "teamOrganization"
WHERE "teamId" = $1
`

func (q *Queries) DeleteTeamOrganizationsForTeam(ctx context.Context, teamId string) error {
	_, err := q.db.ExecContext(ctx, deleteTeamOrganizationsForTeam, teamId)
	return err
}

const deleteTeamMembersForTeam = `-- name: DeleteTeamMembersForTeam :exec
DELETE FROM "teamMember"
WHERE "teamId" = $1
`

func (q *Queries) DeleteTeamMembersForTeam(ctx context.Context, teamId string) error {
	_, err := q.db.ExecContext(ctx, deleteTeamMembersForTeam, teamId)
	return err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM "team"
WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTeam, id)
	return err
}

const updateOrgDetails = `-- name: UpdateOrgDetails :exec
UPDATE "organization"
SET "slug" = $1,
    "updatedAt" = $2,
    "name" = COALESCE($3, "name"),
    "description" = CASE WHEN $4::boolean THEN NULL ELSE COALESCE($5, "description") END,
    "logo" = CASE WHEN $6::boolean THEN NULL ELSE COALESCE($7, "logo") END,
    "discordInvite" = COALESCE($8, "discordInvite"),
    "vrchatGroupId" = COALESCE($9, "vrchatGroupId")
WHERE id = $10
`

type UpdateOrgDetailsParams struct {
	Slug             string
	UpdatedAt        sql.NullTime
	Name             sql.NullString
	ClearDescription bool
	Description      sql.NullString
	ClearLogo        bool
	Logo             sql.NullString
	DiscordInvite    sql.NullString
	VrchatGroupId    sql.NullString
	ID               string
}

func (q *Queries) UpdateOrgDetails(ctx context.Context, arg UpdateOrgDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updateOrgDetails,
		arg.Slug,
		arg.UpdatedAt,
		arg.Name,
		arg.ClearDescription,
		arg.Description,
		arg.ClearLogo,
		arg.Logo,
		arg.DiscordInvite,
		arg.VrchatGroupId,
		arg.ID,
	)
	return err
}

const countAdminOrgs = `-- name: CountAdminOrgs :one
SELECT COUNT(*) FROM "organization"
`

func (q *Queries) CountAdminOrgs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminOrgs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminOrgsBySearch = `-- name: CountAdminOrgsBySearch :one
SELECT COUNT(*) FROM "organization"
WHERE name ILIKE '%' || $1::text || '%' OR slug ILIKE '%' || $1::text || '%'
`

func (q *Queries) CountAdminOrgsBySearch(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminOrgsBySearch, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type AdminOrgRow struct {
	ID                string
	Name              string
	Slug              string
	Logo              sql.NullString
	Description       sql.NullString
	OrgType           sql.NullString
	Status            sql.NullString
	DiscordInvite     sql.NullString
	VrchatGroupId     sql.NullString
	SubmittedByUserId sql.NullString
	CreatedAt         time.Time
	UpdatedAt         sql.NullTime
}

const listAdminOrgs = `-- name: ListAdminOrgs :many
SELECT id, name, slug, logo, description, "orgType", status, "discordInvite", "vrchatGroupId", "submittedByUserId", "createdAt", "updatedAt"
FROM "organization"
ORDER BY name ASC
LIMIT NULLIF($1::int, 0) OFFSET $2
`

type ListAdminOrgsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAdminOrgs(ctx context.Context, arg ListAdminOrgsParams) ([]AdminOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminOrgs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminOrgRow
	for rows.Next() {
		var i AdminOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.Description,
			&i.OrgType,
			&i.Status,
			&i.DiscordInvite,
			&i.VrchatGroupId,
			&i.SubmittedByUserId,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminOrgsBySearch = `-- name: ListAdminOrgsBySearch :many
SELECT id, name, slug, logo, description, "orgType", status, "discordInvite", "vrchatGroupId", "submittedByUserId", "createdAt", "updatedAt"
FROM "organization"
WHERE name ILIKE '%' || $1::text || '%' OR slug ILIKE '%' || $1::text || '%'
ORDER BY name ASC
LIMIT NULLIF($2::int, 0) OFFSET $3
`

type ListAdminOrgsBySearchParams struct {
	Search string
	Limit  int32
	Offset int32
}

func (q *Queries) ListAdminOrgsBySearch(ctx context.Context, arg ListAdminOrgsBySearchParams) ([]AdminOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminOrgsBySearch, arg.Search, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminOrgRow
	for rows.Next() {
		var i AdminOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.Description,
			&i.OrgType,
			&i.Status,
			&i.DiscordInvite,
			&i.VrchatGroupId,
			&i.SubmittedByUserId,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrgByID = `-- name: GetOrgByID :one

SELECT id, name, slug, logo, description, "orgType", status, "discordInvite", "vrchatGroupId", "submittedByUserId", "createdAt", "updatedAt", "rankingAverage", "pointsAverage", "seasonRank", "averagePointsPerEvent"
FROM "organization" WHERE id = $1
`

type GetOrgByIDRow struct {
	ID                    string
	Name                  string
	Slug                  string
	Logo                  sql.NullString
	Description           sql.NullString
	OrgType               sql.NullString
	Status                sql.NullString
	DiscordInvite         sql.NullString
	VrchatGroupId         sql.NullString
	SubmittedByUserId     sql.NullString
	CreatedAt             time.Time
	UpdatedAt             sql.NullTime
	RankingAverage        sql.NullFloat64
	PointsAverage         sql.NullFloat64
	SeasonRank            sql.NullInt32
	AveragePointsPerEvent sql.NullFloat64
}

// Organization lookups and CRUD
func (q *Queries) GetOrgByID(ctx context.Context, id string) (GetOrgByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getOrgByID, id)
	var i GetOrgByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.Description,
		&i.OrgType,
		&i.Status,
		&i.DiscordInvite,
		&i.VrchatGroupId,
		&i.SubmittedByUserId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RankingAverage,
		&i.PointsAverage,
		&i.SeasonRank,
		&i.AveragePointsPerEvent,
	)
	return i, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
SELECT id, name, slug, logo, description, "orgType", status, "discordInvite", "vrchatGroupId", "submittedByUserId", "createdAt", "updatedAt", "rankingAverage", "pointsAverage", "seasonRank", "averagePointsPerEvent"
FROM "organization" WHERE slug = $1
`

type GetOrgBySlugRow struct {
	ID                    string
	Name                  string
	Slug                  string
	Logo                  sql.NullString
	Description           sql.NullString
	OrgType               sql.NullString
	Status                sql.NullString
	DiscordInvite         sql.NullString
	VrchatGroupId         sql.NullString
	SubmittedByUserId     sql.NullString
	CreatedAt             time.Time
	UpdatedAt             sql.NullTime
	RankingAverage        sql.NullFloat64
	PointsAverage         sql.NullFloat64
	SeasonRank            sql.NullInt32
	AveragePointsPerEvent sql.NullFloat64
}

func (q *Queries) GetOrgBySlug(ctx context.Context, slug string) (GetOrgBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getOrgBySlug, slug)
	var i GetOrgBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.Description,
		&i.OrgType,
		&i.Status,
		&i.DiscordInvite,
		&i.VrchatGroupId,
		&i.SubmittedByUserId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RankingAverage,
		&i.PointsAverage,
		&i.SeasonRank,
		&i.AveragePointsPerEvent,
	)
	return i, err
}

const getPrimaryOrgForTeam = `-- name: GetPrimaryOrgForTeam :one
SELECT o.id, o.name, o.slug, o.logo, o.description, o."orgType", o.status
FROM "organization" o
JOIN "teamOrganization" tor ON o.id = tor."organizationId"
WHERE tor."teamId" = $1 AND tor."isPrimary" = true
`

type GetPrimaryOrgForTeamRow struct {
	ID          string
	Name        string
	Slug        string
	Logo        sql.NullString
	Description sql.NullString
	OrgType     sql.NullString
	Status      sql.NullString
}

func (q *Queries) GetPrimaryOrgForTeam(ctx context.Context, teamid string) (GetPrimaryOrgForTeamRow, error) {
	row := q.db.QueryRowContext(ctx, getPrimaryOrgForTeam, teamid)
	var i GetPrimaryOrgForTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.Description,
		&i.OrgType,
		&i.Status,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, slug, logo, description, status, "submittedByUserId", "reviewedByUserId", "reviewedAt", "createdAt", "updatedAt"
FROM "team" WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.Description,
		&i.Status,
		&i.SubmittedByUserId,
		&i.ReviewedByUserId,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamBySlug = `-- name: GetTeamBySlug :one
SELECT id, name, slug, logo, description, status, "submittedByUserId", "reviewedByUserId", "reviewedAt", "createdAt", "updatedAt"
FROM "team" WHERE slug = $1
`

func (q *Queries) GetTeamBySlug(ctx context.Context, slug string) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamBySlug, slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.Description,
		&i.Status,
		&i.SubmittedByUserId,
		&i.ReviewedByUserId,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMember = `-- name: InsertMember :exec
INSERT INTO "member" (id, "organizationId", "userId", role)
VALUES (gen_random_uuid()::text, $1, $2, $3)
`

type InsertMemberParams struct {
	OrganizationId string
	UserId         string
	Role           string
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertMember, arg.OrganizationId, arg.UserId, arg.Role)
	return err
}

const insertTeamMemberRow = `-- name: InsertTeamMemberRow :exec

INSERT INTO "teamMember" (id, "teamId", "userId", role)
VALUES (gen_random_uuid()::text, $1, $2, $3)
`

type InsertTeamMemberRowParams struct {
	TeamId string
	UserId string
	Role   sql.NullString
}

// Member / Roster queries for Team (`teamMember` table)
func (q *Queries) InsertTeamMemberRow(ctx context.Context, arg InsertTeamMemberRowParams) error {
	_, err := q.db.ExecContext(ctx, insertTeamMemberRow, arg.TeamId, arg.UserId, arg.Role)
	return err
}

const insertTeamOrganization = `-- name: InsertTeamOrganization :exec

INSERT INTO "teamOrganization" ("teamId", "organizationId", "isPrimary", "createdAt")
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
`

type InsertTeamOrganizationParams struct {
	TeamId         string
	OrganizationId string
	IsPrimary      bool
}

// teamOrganization queries
func (q *Queries) InsertTeamOrganization(ctx context.Context, arg InsertTeamOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, insertTeamOrganization, arg.TeamId, arg.OrganizationId, arg.IsPrimary)
	return err
}

const listApprovedOrgs = `-- name: ListApprovedOrgs :many
SELECT id, name, slug, logo, description, "orgType", status
FROM "organization"
WHERE status = 'APPROVED'
ORDER BY name ASC
`

type ListApprovedOrgsRow struct {
	ID          string
	Name        string
	Slug        string
	Logo        sql.NullString
	Description sql.NullString
	OrgType     sql.NullString
	Status      sql.NullString
}

func (q *Queries) ListApprovedOrgs(ctx context.Context) ([]ListApprovedOrgsRow, error) {
	rows, err := q.db.QueryContext(ctx, listApprovedOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApprovedOrgsRow
	for rows.Next() {
		var i ListApprovedOrgsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.Description,
			&i.OrgType,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberRows = `-- name: ListMemberRows :many
SELECT m."userId", m.role, u.name, u."vrchatUsername", u.slug, u.image
FROM "member" m JOIN "user" u ON u.id = m."userId"
WHERE m."organizationId" = $1 ORDER BY m."createdAt" ASC
`

type ListMemberRowsRow struct {
	UserId         string
	Role           string
	Name           string
	VrchatUsername sql.NullString
	Slug           sql.NullString
	Image          sql.NullString
}

func (q *Queries) ListMemberRows(ctx context.Context, organizationid string) ([]ListMemberRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMemberRows, organizationid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemberRowsRow
	for rows.Next() {
		var i ListMemberRowsRow
		if err := rows.Scan(
			&i.UserId,
			&i.Role,
			&i.Name,
			&i.VrchatUsername,
			&i.Slug,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsForTeam = `-- name: ListOrgsForTeam :many
SELECT o.id, o.name, o.slug, o.logo, o.description, o."orgType", o.status, tor."isPrimary"
FROM "organization" o
JOIN "teamOrganization" tor ON o.id = tor."organizationId"
WHERE tor."teamId" = $1
ORDER BY tor."isPrimary" DESC, o.name ASC
`

type ListOrgsForTeamRow struct {
	ID          string
	Name        string
	Slug        string
	Logo        sql.NullString
	Description sql.NullString
	OrgType     sql.NullString
	Status      sql.NullString
	IsPrimary   bool
}

func (q *Queries) ListOrgsForTeam(ctx context.Context, teamid string) ([]ListOrgsForTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrgsForTeam, teamid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgsForTeamRow
	for rows.Next() {
		var i ListOrgsForTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.Description,
			&i.OrgType,
			&i.Status,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsForTeamsBatch = `-- name: ListOrgsForTeamsBatch :many
SELECT tor."teamId", o.id, o.name, o.slug, o.logo, o.description, o."orgType", o.status, tor."isPrimary"
FROM "organization" o
JOIN "teamOrganization" tor ON o.id = tor."organizationId"
WHERE tor."teamId" = ANY($1::text[])
ORDER BY tor."isPrimary" DESC, o.name ASC
`

type ListOrgsForTeamsBatchRow struct {
	TeamId      string
	ID          string
	Name        string
	Slug        string
	Logo        sql.NullString
	Description sql.NullString
	OrgType     sql.NullString
	Status      sql.NullString
	IsPrimary   bool
}

func (q *Queries) ListOrgsForTeamsBatch(ctx context.Context, dollar_1 []string) ([]ListOrgsForTeamsBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrgsForTeamsBatch, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgsForTeamsBatchRow
	for rows.Next() {
		var i ListOrgsForTeamsBatchRow
		if err := rows.Scan(
			&i.TeamId,
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.Description,
			&i.OrgType,
			&i.Status,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOrgs = `-- name: ListPendingOrgs :many
SELECT id, name, slug, logo, description, "orgType", status, "discordInvite", "vrchatGroupId", "submittedByUserId", "createdAt", "updatedAt"
FROM "organization"
WHERE status = 'PENDING'
ORDER BY "createdAt" ASC
`

type ListPendingOrgsRow struct {
	ID                string
	Name              string
	Slug              string
	Logo              sql.NullString
	Description       sql.NullString
	OrgType           sql.NullString
	Status            sql.NullString
	DiscordInvite     sql.NullString
	VrchatGroupId     sql.NullString
	SubmittedByUserId sql.NullString
	CreatedAt         time.Time
	UpdatedAt         sql.NullTime
}

func (q *Queries) ListPendingOrgs(ctx context.Context) ([]ListPendingOrgsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingOrgsRow
	for rows.Next() {
		var i ListPendingOrgsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.Description,
			&i.OrgType,
			&i.Status,
			&i.DiscordInvite,
			&i.VrchatGroupId,
			&i.SubmittedByUserId,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTeams = `-- name: ListPendingTeams :many
SELECT id, name, slug, logo, description, status, "submittedByUserId", "createdAt", "updatedAt"
FROM "team"
WHERE status = 'PENDING'
ORDER BY "createdAt" ASC
`

type ListPendingTeamsRow struct {
	ID                string
	Name              string
	Slug              string
	Logo              sql.NullString
	Description       sql.NullString
	Status            string
	SubmittedByUserId sql.NullString
	CreatedAt         time.Time
	UpdatedAt         sql.NullTime
}

func (q *Queries) ListPendingTeams(ctx context.Context) ([]ListPendingTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingTeamsRow
	for rows.Next() {
		var i ListPendingTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.Description,
			&i.Status,
			&i.SubmittedByUserId,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRosterForTeam = `-- name: ListRosterForTeam :many
SELECT tm."userId", tm.role, u.name, u."vrchatUsername", u.slug, u.image
FROM "teamMember" tm JOIN "user" u ON u.id = tm."userId"
WHERE tm."teamId" = $1 ORDER BY tm."createdAt" ASC
`

type ListRosterForTeamRow struct {
	UserId         string
	Role           sql.NullString
	Name           string
	VrchatUsername sql.NullString
	Slug           sql.NullString
	Image          sql.NullString
}

func (q *Queries) ListRosterForTeam(ctx context.Context, teamid string) ([]ListRosterForTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listRosterForTeam, teamid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRosterForTeamRow
	for rows.Next() {
		var i ListRosterForTeamRow
		if err := rows.Scan(
			&i.UserId,
			&i.Role,
			&i.Name,
			&i.VrchatUsername,
			&i.Slug,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRosterForTeamsBatch = `-- name: ListRosterForTeamsBatch :many
SELECT tm."teamId", tm."userId", tm.role, u.name, u."vrchatUsername", u.slug, u.image
FROM "teamMember" tm JOIN "user" u ON u.id = tm."userId"
WHERE tm."teamId" = ANY($1::text[]) ORDER BY tm."createdAt" ASC
`

type ListRosterForTeamsBatchRow struct {
	TeamId         string
	UserId         string
	Role           sql.NullString
	Name           string
	VrchatUsername sql.NullString
	Slug           sql.NullString
	Image          sql.NullString
}

func (q *Queries) ListRosterForTeamsBatch(ctx context.Context, dollar_1 []string) ([]ListRosterForTeamsBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, listRosterForTeamsBatch, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRosterForTeamsBatchRow
	for rows.Next() {
		var i ListRosterForTeamsBatchRow
		if err := rows.Scan(
			&i.TeamId,
			&i.UserId,
			&i.Role,
			&i.Name,
			&i.VrchatUsername,
			&i.Slug,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMemberRows = `-- name: ListTeamMemberRows :many
SELECT m."userId", m.role, u.name, u."vrchatUsername", u.slug, u.image
FROM "member" m JOIN "user" u ON u.id = m."userId"
WHERE m."organizationId" = $1 ORDER BY m."createdAt" ASC
LIMIT NULLIF($2::int, 0) OFFSET $3
`

type ListTeamMemberRowsParams struct {
	OrganizationId string
	Column2        int32
	Offset         int32
}

type ListTeamMemberRowsRow struct {
	UserId         string
	Role           string
	Name           string
	VrchatUsername sql.NullString
	Slug           sql.NullString
	Image          sql.NullString
}

func (q *Queries) ListTeamMemberRows(ctx context.Context, arg ListTeamMemberRowsParams) ([]ListTeamMemberRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMemberRows, arg.OrganizationId, arg.Column2, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMemberRowsRow
	for rows.Next() {
		var i ListTeamMemberRowsRow
		if err := rows.Scan(
			&i.UserId,
			&i.Role,
			&i.Name,
			&i.VrchatUsername,
			&i.Slug,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMemberRowsBySearch = `-- name: ListTeamMemberRowsBySearch :many
SELECT m."userId", m.role, u.name, u."vrchatUsername", u.slug, u.image
FROM "member" m JOIN "user" u ON u.id = m."userId"
WHERE m."organizationId" = $1
  AND (u.name ILIKE '%' || $2::text || '%' OR u."vrchatUsername" ILIKE '%' || $2::text || '%' OR u.slug ILIKE '%' || $2::text || '%')
ORDER BY m."createdAt" ASC
LIMIT NULLIF($3::int, 0) OFFSET $4
`

type ListTeamMemberRowsBySearchParams struct {
	OrganizationId string
	Column2        string
	Column3        int32
	Offset         int32
}

type ListTeamMemberRowsBySearchRow struct {
	UserId         string
	Role           string
	Name           string
	VrchatUsername sql.NullString
	Slug           sql.NullString
	Image          sql.NullString
}

func (q *Queries) ListTeamMemberRowsBySearch(ctx context.Context, arg ListTeamMemberRowsBySearchParams) ([]ListTeamMemberRowsBySearchRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMemberRowsBySearch,
		arg.OrganizationId,
		arg.Column2,
		arg.Column3,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMemberRowsBySearchRow
	for rows.Next() {
		var i ListTeamMemberRowsBySearchRow
		if err := rows.Scan(
			&i.UserId,
			&i.Role,
			&i.Name,
			&i.VrchatUsername,
			&i.Slug,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamRows = `-- name: ListTeamRows :many
SELECT id, name, slug, logo, description, status FROM "team"
WHERE status = 'APPROVED'
ORDER BY name ASC LIMIT NULLIF($1::int, 0) OFFSET $2
`

type ListTeamRowsParams struct {
	Column1 int32
	Offset  int32
}

type ListTeamRowsRow struct {
	ID          string
	Name        string
	Slug        string
	Logo        sql.NullString
	Description sql.NullString
	Status      string
}

func (q *Queries) ListTeamRows(ctx context.Context, arg ListTeamRowsParams) ([]ListTeamRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamRows, arg.Column1, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamRowsRow
	for rows.Next() {
		var i ListTeamRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.Description,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamRowsBySearch = `-- name: ListTeamRowsBySearch :many
SELECT id, name, slug, logo, description, status FROM "team"
WHERE status = 'APPROVED' AND (name ILIKE '%' || $1::text || '%' OR slug ILIKE '%' || $1::text || '%')
ORDER BY name ASC LIMIT NULLIF($2::int, 0) OFFSET $3
`

type ListTeamRowsBySearchParams struct {
	Column1 string
	Column2 int32
	Offset  int32
}

type ListTeamRowsBySearchRow struct {
	ID          string
	Name        string
	Slug        string
	Logo        sql.NullString
	Description sql.NullString
	Status      string
}

func (q *Queries) ListTeamRowsBySearch(ctx context.Context, arg ListTeamRowsBySearchParams) ([]ListTeamRowsBySearchRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamRowsBySearch, arg.Column1, arg.Column2, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamRowsBySearchRow
	for rows.Next() {
		var i ListTeamRowsBySearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.Description,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForOrg = `-- name: ListTeamsForOrg :many
SELECT t.id, t.name, t.slug, t.logo, t.description, t.status, tor."isPrimary"
FROM "team" t
JOIN "teamOrganization" tor ON t.id = tor."teamId"
WHERE tor."organizationId" = $1
ORDER BY t.name ASC
`

type ListTeamsForOrgRow struct {
	ID          string
	Name        string
	Slug        string
	Logo        sql.NullString
	Description sql.NullString
	Status      string
	IsPrimary   bool
}

func (q *Queries) ListTeamsForOrg(ctx context.Context, organizationid string) ([]ListTeamsForOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamsForOrg, organizationid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsForOrgRow
	for rows.Next() {
		var i ListTeamsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.Description,
			&i.Status,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberIDByOrgAndUser = `-- name: MemberIDByOrgAndUser :one
SELECT id FROM "member" WHERE "organizationId" = $1 AND "userId" = $2
`

type MemberIDByOrgAndUserParams struct {
	OrganizationId string
	UserId         string
}

func (q *Queries) MemberIDByOrgAndUser(ctx context.Context, arg MemberIDByOrgAndUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, memberIDByOrgAndUser, arg.OrganizationId, arg.UserId)
	var id string
	err := row.Scan(&id)
	return id, err
}

const memberRoleByOrgAndUser = `-- name: MemberRoleByOrgAndUser :one
SELECT role FROM "member" WHERE "organizationId" = $1 AND "userId" = $2
`

type MemberRoleByOrgAndUserParams struct {
	OrganizationId string
	UserId         string
}

func (q *Queries) MemberRoleByOrgAndUser(ctx context.Context, arg MemberRoleByOrgAndUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, memberRoleByOrgAndUser, arg.OrganizationId, arg.UserId)
	var role string
	err := row.Scan(&role)
	return role, err
}

const orgIDByID = `-- name: OrgIDByID :one
SELECT id FROM "organization" WHERE id = $1
`

func (q *Queries) OrgIDByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, orgIDByID, id)
	err := row.Scan(&id)
	return id, err
}

const orgIDBySlug = `-- name: OrgIDBySlug :one
SELECT id FROM "organization" WHERE slug = $1
`

func (q *Queries) OrgIDBySlug(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRowContext(ctx, orgIDBySlug, slug)
	var id string
	err := row.Scan(&id)
	return id, err
}

const orgSlugByID = `-- name: OrgSlugByID :one
SELECT slug FROM "organization" WHERE id = $1
`

func (q *Queries) OrgSlugByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, orgSlugByID, id)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const teamIDBySlug = `-- name: TeamIDBySlug :one
SELECT id FROM "team" WHERE slug = $1
`

func (q *Queries) TeamIDBySlug(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRowContext(ctx, teamIDBySlug, slug)
	var id string
	err := row.Scan(&id)
	return id, err
}

const teamSlugByID = `-- name: TeamSlugByID :one
SELECT slug FROM "team" WHERE id = $1
`

func (q *Queries) TeamSlugByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, teamSlugByID, id)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const touchOrg = `-- name: TouchOrg :exec
UPDATE "organization" SET "updatedAt" = $1 WHERE id = $2
`

type TouchOrgParams struct {
	UpdatedAt sql.NullTime
	ID        string
}

func (q *Queries) TouchOrg(ctx context.Context, arg TouchOrgParams) error {
	_, err := q.db.ExecContext(ctx, touchOrg, arg.UpdatedAt, arg.ID)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE "member" SET role = $1 WHERE "organizationId" = $2 AND "userId" = $3
`

type UpdateMemberRoleParams struct {
	Role           string
	OrganizationId string
	UserId         string
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberRole, arg.Role, arg.OrganizationId, arg.UserId)
	return err
}

const updateOrg = `-- name: UpdateOrg :exec
UPDATE "organization"
SET "slug" = $1,
    "updatedAt" = $2,
    "name" = COALESCE($3, "name"),
    "description" = CASE WHEN $4::boolean THEN NULL ELSE COALESCE($5, "description") END,
    "logo" = CASE WHEN $6::boolean THEN NULL ELSE COALESCE($7, "logo") END
WHERE id = $8
`

type UpdateOrgParams struct {
	Slug             string
	UpdatedAt        sql.NullTime
	Name             sql.NullString
	ClearDescription bool
	Description      sql.NullString
	ClearLogo        bool
	Logo             sql.NullString
	ID               string
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) error {
	_, err := q.db.ExecContext(ctx, updateOrg,
		arg.Slug,
		arg.UpdatedAt,
		arg.Name,
		arg.ClearDescription,
		arg.Description,
		arg.ClearLogo,
		arg.Logo,
		arg.ID,
	)
	return err
}

const updateOrgStatus = `-- name: UpdateOrgStatus :exec
UPDATE "organization"
SET status = $1, "updatedAt" = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateOrgStatusParams struct {
	Status sql.NullString
	ID     string
}

func (q *Queries) UpdateOrgStatus(ctx context.Context, arg UpdateOrgStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrgStatus, arg.Status, arg.ID)
	return err
}

const updateTeam = `-- name: UpdateTeam :exec
UPDATE "team"
SET "slug" = $1,
    "updatedAt" = $2,
    "name" = COALESCE($3, "name"),
    "description" = CASE WHEN $4::boolean THEN NULL ELSE COALESCE($5, "description") END,
    "logo" = CASE WHEN $6::boolean THEN NULL ELSE COALESCE($7, "logo") END
WHERE id = $8
`

type UpdateTeamParams struct {
	Slug             string
	UpdatedAt        sql.NullTime
	Name             sql.NullString
	ClearDescription bool
	Description      sql.NullString
	ClearLogo        bool
	Logo             sql.NullString
	ID               string
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) error {
	_, err := q.db.ExecContext(ctx, updateTeam,
		arg.Slug,
		arg.UpdatedAt,
		arg.Name,
		arg.ClearDescription,
		arg.Description,
		arg.ClearLogo,
		arg.Logo,
		arg.ID,
	)
	return err
}

const updateTeamMemberRoleRow = `-- name: UpdateTeamMemberRoleRow :exec
UPDATE "teamMember" SET role = $1 WHERE "teamId" = $2 AND "userId" = $3
`

type UpdateTeamMemberRoleRowParams struct {
	Role   sql.NullString
	TeamId string
	UserId string
}

func (q *Queries) UpdateTeamMemberRoleRow(ctx context.Context, arg UpdateTeamMemberRoleRowParams) error {
	_, err := q.db.ExecContext(ctx, updateTeamMemberRoleRow, arg.Role, arg.TeamId, arg.UserId)
	return err
}

const updateTeamStats = `-- name: UpdateTeamStats :exec
UPDATE "organization"
SET "rankingAverage" = COALESCE($1, "rankingAverage"),
    "pointsAverage" = COALESCE($2, "pointsAverage"),
    "seasonRank" = COALESCE($3, "seasonRank"),
    "averagePointsPerEvent" = COALESCE($4, "averagePointsPerEvent")
WHERE id = $5
`

type UpdateTeamStatsParams struct {
	RankingAverage        sql.NullFloat64
	PointsAverage         sql.NullFloat64
	SeasonRank            sql.NullInt32
	AveragePointsPerEvent sql.NullFloat64
	ID                    string
}

// Team stats update
func (q *Queries) UpdateTeamStats(ctx context.Context, arg UpdateTeamStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateTeamStats,
		arg.RankingAverage,
		arg.PointsAverage,
		arg.SeasonRank,
		arg.AveragePointsPerEvent,
		arg.ID,
	)
	return err
}

const updateTeamStatus = `-- name: UpdateTeamStatus :exec
UPDATE "team"
SET status = $1,
    "reviewedByUserId" = $2,
    "reviewedAt" = $3,
    "updatedAt" = CURRENT_TIMESTAMP
WHERE id = $4
`

type UpdateTeamStatusParams struct {
	Status           string
	ReviewedByUserId sql.NullString
	ReviewedAt       sql.NullTime
	ID               string
}

func (q *Queries) UpdateTeamStatus(ctx context.Context, arg UpdateTeamStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTeamStatus,
		arg.Status,
		arg.ReviewedByUserId,
		arg.ReviewedAt,
		arg.ID,
	)
	return err
}

const userIDByID = `-- name: UserIDByID :one
SELECT id FROM "user" WHERE id = $1
`

func (q *Queries) UserIDByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, userIDByID, id)
	err := row.Scan(&id)
	return id, err
}
