// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worker.sql

package sqlc

import (
	"context"
	"database/sql"
)

const claimTask = `-- name: ClaimTask :exec
UPDATE "score_calc_task" SET status = 'PROCESSING', attempts = $1, "startedAt" = $2 WHERE id = $3
`

type ClaimTaskParams struct {
	Attempts  int32
	StartedAt sql.NullTime
	ID        string
}

func (q *Queries) ClaimTask(ctx context.Context, arg ClaimTaskParams) error {
	_, err := q.db.ExecContext(ctx, claimTask, arg.Attempts, arg.StartedAt, arg.ID)
	return err
}

const failTask = `-- name: FailTask :exec
UPDATE "score_calc_task" SET status = 'FAILED', "lastError" = $1, "completedAt" = $2 WHERE id = $3
`

type FailTaskParams struct {
	LastError   sql.NullString
	CompletedAt sql.NullTime
	ID          string
}

func (q *Queries) FailTask(ctx context.Context, arg FailTaskParams) error {
	_, err := q.db.ExecContext(ctx, failTask, arg.LastError, arg.CompletedAt, arg.ID)
	return err
}

const getEventScoringType = `-- name: GetEventScoringType :one

SELECT "scoringType" FROM "event" WHERE id = $1
`

// Source data for the projection.
func (q *Queries) GetEventScoringType(ctx context.Context, id string) (int16, error) {
	row := q.db.QueryRowContext(ctx, getEventScoringType, id)
	var scoringType int16
	err := row.Scan(&scoringType)
	return scoringType, err
}

const getLatestGenerationState = `-- name: GetLatestGenerationState :one
SELECT "latestGeneration" FROM "score_calc_state" WHERE "eventId" = $1
`

func (q *Queries) GetLatestGenerationState(ctx context.Context, eventid string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getLatestGenerationState, eventid)
	var latestGeneration int32
	err := row.Scan(&latestGeneration)
	return latestGeneration, err
}

const getTaskForClaim = `-- name: GetTaskForClaim :one

SELECT id, "eventId", generation, status, attempts
FROM "score_calc_task" WHERE id = $1
`

type GetTaskForClaimRow struct {
	ID         string
	EventId    string
	Generation int32
	Status     string
	Attempts   int32
}

// Claim: load the task and fence against newer generations.
func (q *Queries) GetTaskForClaim(ctx context.Context, id string) (GetTaskForClaimRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskForClaim, id)
	var i GetTaskForClaimRow
	err := row.Scan(
		&i.ID,
		&i.EventId,
		&i.Generation,
		&i.Status,
		&i.Attempts,
	)
	return i, err
}

const listEventMemberUserIDs = `-- name: ListEventMemberUserIDs :many
SELECT "userId" FROM "event_member" WHERE "eventId" = $1
`

func (q *Queries) ListEventMemberUserIDs(ctx context.Context, eventid string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEventMemberUserIDs, eventid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var userId string
		if err := rows.Scan(&userId); err != nil {
			return nil, err
		}
		items = append(items, userId)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRaceResultInputs = `-- name: ListRaceResultInputs :many
SELECT r."userId", r.points FROM "race_result" r
JOIN "race_event" re ON re.id = r."raceEventId"
WHERE re."eventId" = $1
`

type ListRaceResultInputsRow struct {
	UserId string
	Points int32
}

func (q *Queries) ListRaceResultInputs(ctx context.Context, eventid string) ([]ListRaceResultInputsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRaceResultInputs, eventid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRaceResultInputsRow
	for rows.Next() {
		var i ListRaceResultInputsRow
		if err := rows.Scan(&i.UserId, &i.Points); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskSuperseded = `-- name: MarkTaskSuperseded :exec
UPDATE "score_calc_task" SET status = 'SUPERSEDED' WHERE id = $1
`

func (q *Queries) MarkTaskSuperseded(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markTaskSuperseded, id)
	return err
}

const supersedeTaskWithError = `-- name: SupersedeTaskWithError :exec
UPDATE "score_calc_task" SET status = 'SUPERSEDED', "lastError" = $1, "completedAt" = $2 WHERE id = $3
`

type SupersedeTaskWithErrorParams struct {
	LastError   sql.NullString
	CompletedAt sql.NullTime
	ID          string
}

func (q *Queries) SupersedeTaskWithError(ctx context.Context, arg SupersedeTaskWithErrorParams) error {
	_, err := q.db.ExecContext(ctx, supersedeTaskWithError, arg.LastError, arg.CompletedAt, arg.ID)
	return err
}
