/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTeamsIndexRouteImport } from './routes/admin/teams/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminTeamsTeamIdRouteImport } from './routes/admin/teams/$teamId'
import { Route as AdminEventsEventIdRouteImport } from './routes/admin/events/$eventId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsIndexRoute = AdminTeamsIndexRouteImport.update({
  id: '/admin/teams/',
  path: '/admin/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsTeamIdRoute = AdminTeamsTeamIdRouteImport.update({
  id: '/admin/teams/$teamId',
  path: '/admin/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventIdRoute = AdminEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AdminEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/teams/': typeof AdminTeamsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/teams': typeof AdminTeamsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/teams/': typeof AdminTeamsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/admin/events'
    | '/events/$eventId'
    | '/admin/'
    | '/events/'
    | '/profile/'
    | '/admin/events/$eventId'
    | '/admin/teams/$teamId'
    | '/admin/users/$userId'
    | '/admin/teams/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/admin/events'
    | '/events/$eventId'
    | '/admin'
    | '/events'
    | '/profile'
    | '/admin/events/$eventId'
    | '/admin/teams/$teamId'
    | '/admin/users/$userId'
    | '/admin/teams'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/admin/events'
    | '/events/$eventId'
    | '/admin/'
    | '/events/'
    | '/profile/'
    | '/admin/events/$eventId'
    | '/admin/teams/$teamId'
    | '/admin/users/$userId'
    | '/admin/teams/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  EventsEventIdRoute: typeof EventsEventIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  AdminTeamsTeamIdRoute: typeof AdminTeamsTeamIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminTeamsIndexRoute: typeof AdminTeamsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams/': {
      id: '/admin/teams/'
      path: '/admin/teams'
      fullPath: '/admin/teams/'
      preLoaderRoute: typeof AdminTeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams/$teamId': {
      id: '/admin/teams/$teamId'
      path: '/admin/teams/$teamId'
      fullPath: '/admin/teams/$teamId'
      preLoaderRoute: typeof AdminTeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId': {
      id: '/admin/events/$eventId'
      path: '/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AdminEventsEventIdRouteImport
      parentRoute: typeof AdminEventsRoute
    }
  }
}

interface AdminEventsRouteChildren {
  AdminEventsEventIdRoute: typeof AdminEventsEventIdRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsEventIdRoute: AdminEventsEventIdRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  AdminEventsRoute: AdminEventsRouteWithChildren,
  EventsEventIdRoute: EventsEventIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  AdminTeamsTeamIdRoute: AdminTeamsTeamIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminTeamsIndexRoute: AdminTeamsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
