// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const acceptGeneration = `-- name: AcceptGeneration :exec
UPDATE "score_calc_state" SET "acceptedGeneration" = $1 WHERE "eventId" = $2
`

type AcceptGenerationParams struct {
	AcceptedGeneration int32
	EventId            string
}

func (q *Queries) AcceptGeneration(ctx context.Context, arg AcceptGenerationParams) error {
	_, err := q.db.ExecContext(ctx, acceptGeneration, arg.AcceptedGeneration, arg.EventId)
	return err
}

const coalesceGeneration = `-- name: CoalesceGeneration :one

INSERT INTO "score_calc_state" ("eventId", "latestGeneration", "acceptedGeneration", "updatedAt")
VALUES ($1, 1, 0, $2)
ON CONFLICT ("eventId") DO UPDATE SET "latestGeneration" = "score_calc_state"."latestGeneration" + 1
RETURNING "latestGeneration"
`

type CoalesceGenerationParams struct {
	EventId   string
	UpdatedAt time.Time
}

// Generation coalescing: insert the state row or bump the generation,
// returning the generation this job must use.
func (q *Queries) CoalesceGeneration(ctx context.Context, arg CoalesceGenerationParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, coalesceGeneration, arg.EventId, arg.UpdatedAt)
	var latestGeneration int32
	err := row.Scan(&latestGeneration)
	return latestGeneration, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE "score_calc_task" SET status = 'COMPLETED', "completedAt" = $1, "resultChecksum" = $2 WHERE id = $3
`

type CompleteJobParams struct {
	CompletedAt    sql.NullTime
	ResultChecksum sql.NullString
	ID             string
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) error {
	_, err := q.db.ExecContext(ctx, completeJob, arg.CompletedAt, arg.ResultChecksum, arg.ID)
	return err
}

const createJob = `-- name: CreateJob :exec
INSERT INTO "score_calc_task" (id, "eventId", generation, "requestedUserIds", status, attempts, "requestedAt")
VALUES ($1, $2, $3, $4, 'PENDING', 0, $5)
`

type CreateJobParams struct {
	ID               string
	EventId          string
	Generation       int32
	RequestedUserIds pqtype.NullRawMessage
	RequestedAt      time.Time
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.ExecContext(ctx, createJob,
		arg.ID,
		arg.EventId,
		arg.Generation,
		arg.RequestedUserIds,
		arg.RequestedAt,
	)
	return err
}

const failJob = `-- name: FailJob :exec
UPDATE "score_calc_task" SET status = 'FAILED', "lastError" = $1, "completedAt" = $2 WHERE id = $3
`

type FailJobParams struct {
	LastError   sql.NullString
	CompletedAt sql.NullTime
	ID          string
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.ExecContext(ctx, failJob, arg.LastError, arg.CompletedAt, arg.ID)
	return err
}

const getEventScoringType = `-- name: GetEventScoringType :one

SELECT "scoringType" FROM "event" WHERE id = $1
`

// Event lookup.
func (q *Queries) GetEventScoringType(ctx context.Context, id string) (int16, error) {
	row := q.db.QueryRowContext(ctx, getEventScoringType, id)
	var scoringType int16
	err := row.Scan(&scoringType)
	return scoringType, err
}

const getJob = `-- name: GetJob :one

SELECT id, "eventId", generation, "requestedUserIds", status, attempts
FROM "score_calc_task" WHERE id = $1
`

type GetJobRow struct {
	ID               string
	EventId          string
	Generation       int32
	RequestedUserIds pqtype.NullRawMessage
	Status           string
	Attempts         int32
}

// Job lifecycle.
func (q *Queries) GetJob(ctx context.Context, id string) (GetJobRow, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i GetJobRow
	err := row.Scan(
		&i.ID,
		&i.EventId,
		&i.Generation,
		&i.RequestedUserIds,
		&i.Status,
		&i.Attempts,
	)
	return i, err
}

const getLatestGeneration = `-- name: GetLatestGeneration :one
SELECT "latestGeneration" FROM "score_calc_state" WHERE "eventId" = $1
`

func (q *Queries) GetLatestGeneration(ctx context.Context, eventid string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getLatestGeneration, eventid)
	var latestGeneration int32
	err := row.Scan(&latestGeneration)
	return latestGeneration, err
}

const markJobSuperseded = `-- name: MarkJobSuperseded :exec
UPDATE "score_calc_task" SET status = 'SUPERSEDED' WHERE id = $1
`

func (q *Queries) MarkJobSuperseded(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markJobSuperseded, id)
	return err
}

const upsertPointsEntry = `-- name: UpsertPointsEntry :exec
INSERT INTO "event_points_entry" (id, "eventId", "userId", points, "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $5)
ON CONFLICT ("eventId", "userId") DO UPDATE SET points = EXCLUDED.points
`

type UpsertPointsEntryParams struct {
	ID        string
	EventId   string
	UserId    string
	Points    int32
	CreatedAt time.Time
}

func (q *Queries) UpsertPointsEntry(ctx context.Context, arg UpsertPointsEntryParams) error {
	_, err := q.db.ExecContext(ctx, upsertPointsEntry,
		arg.ID,
		arg.EventId,
		arg.UserId,
		arg.Points,
		arg.CreatedAt,
	)
	return err
}
