// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const acceptGeneration = `-- name: AcceptGeneration :exec
UPDATE "score_calc_state" SET "acceptedGeneration" = $1 WHERE "eventId" = $2
`

type AcceptGenerationParams struct {
	AcceptedGeneration int32
	EventId            string
}

func (q *Queries) AcceptGeneration(ctx context.Context, arg AcceptGenerationParams) error {
	_, err := q.db.ExecContext(ctx, acceptGeneration, arg.AcceptedGeneration, arg.EventId)
	return err
}

const batchUpsertPointsEntries = `-- name: BatchUpsertPointsEntries :exec
INSERT INTO "event_points_entry" (id, "eventId", "userId", points, "createdAt", "updatedAt")
SELECT unnest($1::text[]), $2::text, unnest($3::text[]), unnest($4::int[]), $5::timestamp, $5::timestamp
ON CONFLICT ("eventId", "userId") DO UPDATE SET points = EXCLUDED.points
`

type BatchUpsertPointsEntriesParams struct {
	Ids       []string
	EventID   string
	UserIds   []string
	Points    []int32
	CreatedAt time.Time
}

func (q *Queries) BatchUpsertPointsEntries(ctx context.Context, arg BatchUpsertPointsEntriesParams) error {
	_, err := q.db.ExecContext(ctx, batchUpsertPointsEntries,
		pq.Array(arg.Ids),
		arg.EventID,
		pq.Array(arg.UserIds),
		pq.Array(arg.Points),
		arg.CreatedAt,
	)
	return err
}

const calculateLeaderboardStats = `-- name: CalculateLeaderboardStats :many

SELECT
  u.id AS user_id,
  u.name AS name,
  u."vrchatUsername" AS vrchat_username,
  u.slug AS slug,
  u.image AS image,
  COALESCE(u."classTier"::text, '') AS class_tier,
  COALESCE(p.total_points, 0)::int AS total_points,
  COALESCE(r.avg_position, 0)::float8 AS avg_position,
  COALESCE(r.races_participated, 0)::int AS races_participated,
  COALESCE(r.wins, 0)::int AS wins,
  COALESCE(p.events_participated, 0)::int AS events_participated,
  COALESCE(s.seasons_count, 1)::int AS seasons_count,
  CASE
    WHEN COALESCE(s.seasons_count, 1) > 0 THEN COALESCE(p.total_points, 0)::float8 / COALESCE(s.seasons_count, 1)
    ELSE COALESCE(p.total_points, 0)::float8
  END AS avg_points_per_season
FROM "user" u
LEFT JOIN (
  SELECT "userId", SUM(points) AS total_points, COUNT(DISTINCT "eventId") AS events_participated
  FROM "event_points_entry"
  GROUP BY "userId"
) p ON p."userId" = u.id
LEFT JOIN (
  SELECT
    rr."userId",
    AVG(rr.position) FILTER (WHERE rr.position IS NOT NULL AND rr.position > 0) AS avg_position,
    COUNT(DISTINCT rr."raceEventId") AS races_participated,
    COUNT(*) FILTER (WHERE rr.position = 1) AS wins
  FROM "race_result" rr
  GROUP BY rr."userId"
) r ON r."userId" = u.id
LEFT JOIN (
  SELECT
    epe."userId",
    COUNT(DISTINCT EXTRACT(YEAR FROM COALESCE(e."scheduledAt", e."createdAt"))) AS seasons_count
  FROM "event_points_entry" epe
  JOIN "event" e ON e.id = epe."eventId"
  GROUP BY epe."userId"
) s ON s."userId" = u.id
WHERE (COALESCE(p.total_points, 0) > 0 OR COALESCE(r.races_participated, 0) > 0)
ORDER BY total_points DESC
`

type CalculateLeaderboardStatsRow struct {
	UserID             string
	Name               string
	VrchatUsername     sql.NullString
	Slug               sql.NullString
	Image              sql.NullString
	ClassTier          interface{}
	TotalPoints        int32
	AvgPosition        float64
	RacesParticipated  int32
	Wins               int32
	EventsParticipated int32
	SeasonsCount       int32
	AvgPointsPerSeason float64
}

// Leaderboard aggregation.
func (q *Queries) CalculateLeaderboardStats(ctx context.Context) ([]CalculateLeaderboardStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, calculateLeaderboardStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalculateLeaderboardStatsRow
	for rows.Next() {
		var i CalculateLeaderboardStatsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.VrchatUsername,
			&i.Slug,
			&i.Image,
			&i.ClassTier,
			&i.TotalPoints,
			&i.AvgPosition,
			&i.RacesParticipated,
			&i.Wins,
			&i.EventsParticipated,
			&i.SeasonsCount,
			&i.AvgPointsPerSeason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const coalesceGeneration = `-- name: CoalesceGeneration :one

INSERT INTO "score_calc_state" ("eventId", "latestGeneration", "acceptedGeneration", "updatedAt")
VALUES ($1, 1, 0, $2)
ON CONFLICT ("eventId") DO UPDATE SET "latestGeneration" = "score_calc_state"."latestGeneration" + 1
RETURNING "latestGeneration"
`

type CoalesceGenerationParams struct {
	EventId   string
	UpdatedAt time.Time
}

// Generation coalescing: insert the state row or bump the generation,
// returning the generation this job must use.
func (q *Queries) CoalesceGeneration(ctx context.Context, arg CoalesceGenerationParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, coalesceGeneration, arg.EventId, arg.UpdatedAt)
	var latestGeneration int32
	err := row.Scan(&latestGeneration)
	return latestGeneration, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE "score_calc_task" SET status = 'COMPLETED', "completedAt" = $1, "resultChecksum" = $2 WHERE id = $3
`

type CompleteJobParams struct {
	CompletedAt    sql.NullTime
	ResultChecksum sql.NullString
	ID             string
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) error {
	_, err := q.db.ExecContext(ctx, completeJob, arg.CompletedAt, arg.ResultChecksum, arg.ID)
	return err
}

const createJob = `-- name: CreateJob :exec
INSERT INTO "score_calc_task" (id, "eventId", generation, "requestedUserIds", status, attempts, "requestedAt")
VALUES ($1, $2, $3, $4, 'PENDING', 0, $5)
`

type CreateJobParams struct {
	ID               string
	EventId          string
	Generation       int32
	RequestedUserIds pqtype.NullRawMessage
	RequestedAt      time.Time
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.ExecContext(ctx, createJob,
		arg.ID,
		arg.EventId,
		arg.Generation,
		arg.RequestedUserIds,
		arg.RequestedAt,
	)
	return err
}

const failJob = `-- name: FailJob :exec
UPDATE "score_calc_task" SET status = 'FAILED', "lastError" = $1, "completedAt" = $2 WHERE id = $3
`

type FailJobParams struct {
	LastError   sql.NullString
	CompletedAt sql.NullTime
	ID          string
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.ExecContext(ctx, failJob, arg.LastError, arg.CompletedAt, arg.ID)
	return err
}

const getEventScoringType = `-- name: GetEventScoringType :one

SELECT "scoringType" FROM "event" WHERE id = $1
`

// Event lookup.
func (q *Queries) GetEventScoringType(ctx context.Context, id string) (int16, error) {
	row := q.db.QueryRowContext(ctx, getEventScoringType, id)
	var scoringType int16
	err := row.Scan(&scoringType)
	return scoringType, err
}

const getJob = `-- name: GetJob :one

SELECT id, "eventId", generation, "requestedUserIds", status, attempts
FROM "score_calc_task" WHERE id = $1
`

type GetJobRow struct {
	ID               string
	EventId          string
	Generation       int32
	RequestedUserIds pqtype.NullRawMessage
	Status           string
	Attempts         int32
}

// Job lifecycle.
func (q *Queries) GetJob(ctx context.Context, id string) (GetJobRow, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i GetJobRow
	err := row.Scan(
		&i.ID,
		&i.EventId,
		&i.Generation,
		&i.RequestedUserIds,
		&i.Status,
		&i.Attempts,
	)
	return i, err
}

const getLatestGeneration = `-- name: GetLatestGeneration :one
SELECT "latestGeneration" FROM "score_calc_state" WHERE "eventId" = $1
`

func (q *Queries) GetLatestGeneration(ctx context.Context, eventid string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getLatestGeneration, eventid)
	var latestGeneration int32
	err := row.Scan(&latestGeneration)
	return latestGeneration, err
}

const markJobSuperseded = `-- name: MarkJobSuperseded :exec
UPDATE "score_calc_task" SET status = 'SUPERSEDED' WHERE id = $1
`

func (q *Queries) MarkJobSuperseded(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markJobSuperseded, id)
	return err
}

const upsertPointsEntry = `-- name: UpsertPointsEntry :exec
INSERT INTO "event_points_entry" (id, "eventId", "userId", points, "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $5)
ON CONFLICT ("eventId", "userId") DO UPDATE SET points = EXCLUDED.points
`

type UpsertPointsEntryParams struct {
	ID        string
	EventId   string
	UserId    string
	Points    int32
	CreatedAt time.Time
}

func (q *Queries) UpsertPointsEntry(ctx context.Context, arg UpsertPointsEntryParams) error {
	_, err := q.db.ExecContext(ctx, upsertPointsEntry,
		arg.ID,
		arg.EventId,
		arg.UserId,
		arg.Points,
		arg.CreatedAt,
	)
	return err
}
