// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_records.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countUserRaceRecords = `-- name: CountUserRaceRecords :one
SELECT COUNT(*)
FROM "race_result" r
JOIN "race_event" re ON re.id = r."raceEventId"
JOIN "event" e ON e.id = re."eventId"
WHERE r."userId" = $1
`

func (q *Queries) CountUserRaceRecords(ctx context.Context, userid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserRaceRecords, userid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUserRaceRecords = `-- name: ListUserRaceRecords :many
SELECT
    r.id AS "resultId",
    r.position,
    r.points,
    r."finishTime",
    r."resultStatus",
    r."createdAt" AS "resultCreatedAt",
    re.id AS "raceId",
    re.name AS "raceName",
    re.sequence AS "raceSequence",
    re.grade AS "raceGrade",
    e.id AS "eventId",
    e.name AS "eventName",
    e.tag AS "eventTag",
    e."scheduledAt" AS "eventScheduledAt"
FROM "race_result" r
JOIN "race_event" re ON re.id = r."raceEventId"
JOIN "event" e ON e.id = re."eventId"
WHERE r."userId" = $1
ORDER BY e."createdAt" DESC, re.sequence ASC
LIMIT NULLIF($2::int, 0) OFFSET $3::int
`

type ListUserRaceRecordsParams struct {
	UserId  string
	Column2 int32
	Column3 int32
}

type ListUserRaceRecordsRow struct {
	ResultId         string
	Position         sql.NullInt32
	Points           int32
	FinishTime       sql.NullString
	ResultStatus     sql.NullString
	ResultCreatedAt  time.Time
	RaceId           string
	RaceName         string
	RaceSequence     int32
	RaceGrade        sql.NullString
	EventId          string
	EventName        string
	EventTag         string
	EventScheduledAt sql.NullTime
}

// User race records query.
func (q *Queries) ListUserRaceRecords(ctx context.Context, arg ListUserRaceRecordsParams) ([]ListUserRaceRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserRaceRecords, arg.UserId, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRaceRecordsRow
	for rows.Next() {
		var i ListUserRaceRecordsRow
		if err := rows.Scan(
			&i.ResultId,
			&i.Position,
			&i.Points,
			&i.FinishTime,
			&i.ResultStatus,
			&i.ResultCreatedAt,
			&i.RaceId,
			&i.RaceName,
			&i.RaceSequence,
			&i.RaceGrade,
			&i.EventId,
			&i.EventName,
			&i.EventTag,
			&i.EventScheduledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
