// Code generated by the Encore v1.57.9 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-hzvac.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the hzvac Encore application.
 */
export default class Client {
    public readonly auth: auth.ServiceClient
    public readonly eventmanager: eventmanager.ServiceClient
    public readonly frontend: frontend.ServiceClient
    public readonly hello: hello.ServiceClient
    public readonly teammanager: teammanager.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.auth = new auth.ServiceClient(base)
        this.eventmanager = new eventmanager.ServiceClient(base)
        this.frontend = new frontend.ServiceClient(base)
        this.hello = new hello.ServiceClient(base)
        this.teammanager = new teammanager.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: auth.AuthParams | AuthDataGenerator
}

export namespace auth {
    export interface AdminUpdateUserParams {
        authorization: string
        name?: string
        image?: string | null
        biography?: string | null
        careerOverview?: string | null
        classTier?: eventmanager.ClassTier | null
    }

    export interface AuthParams {
        authorization: string
    }

    export interface SetSiteRoleParams {
        authorization: string
        siteRole: SiteRoleName
    }

    /**
     * Global (non-organization) privilege axis. A SITE_ADMIN has absolute control
     * over all data and short-circuits every scoped permission check (see rbac.ts).
     */
    export type SiteRoleName = "USER" | "SITE_ADMIN"

    /**
     * Netkeiba-style participant profile (issue #7). Combines core user info with a
     * biography, a free-form career overview, the participant's skill class tier
     * (issue #3) and their team affiliations (organization memberships, issue #6).
     */
    export interface TeamAffiliation {
        organizationId: string
        name: string
        slug: string
        role: string
    }

    export interface UpdateUserParams {
        authorization: string
        name?: string
        image?: string | null
        biography?: string | null
        careerOverview?: string | null
    }

    export interface UserProfile {
        id: string
        name: string
        email: string
        image: string | null
        biography: string | null
        careerOverview: string | null
        classTier: eventmanager.ClassTier | null
        siteRole: SiteRoleName
        teams: TeamAffiliation[]
        createdAt: string
        updatedAt: string
    }

    /**
     * Lightweight user record for directory listings (no team affiliations or
     * long-form biography/career text).
     */
    export interface UserSummary {
        id: string
        name: string
        email: string
        classTier: eventmanager.ClassTier | null
        siteRole: SiteRoleName
        createdAt: string
        updatedAt: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.adminUpdateUser = this.adminUpdateUser.bind(this)
            this.authHandler = this.authHandler.bind(this)
            this.getUserProfile = this.getUserProfile.bind(this)
            this.listUsers = this.listUsers.bind(this)
            this.setUserSiteRole = this.setUserSiteRole.bind(this)
            this.updateUserProfile = this.updateUserProfile.bind(this)
        }

        /**
         * Admin-only endpoint that edits any user's profile metadata and skill class
         * tier. Distinct from `updateUserProfile`, which is self-service and cannot
         * touch `classTier`. Gated to site administrators so the admin panel is the
         * single place platform-wide profile edits happen.
         */
        public async adminUpdateUser(id: string, params: AdminUpdateUserParams): Promise<UserProfile> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                biography:      params.biography,
                careerOverview: params.careerOverview,
                classTier:      params.classTier,
                image:          params.image,
                name:           params.name,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/admin/users/${encodeURIComponent(id)}`, JSON.stringify(body), {headers})
            return await resp.json() as UserProfile
        }

        /**
         * apparently we don't need anything else more than this according to this docs
         * https://better-auth.com/docs/integrations/encore
         * but I get conflicting information from Encore (maybe older version of better-auth?) because we need a more
         * elaborate version?
         * https://encore.dev/blog/betterauth-tutorial
         * anyways, I will trust better-auth's version for now and if it doesn't work I blame Cairo
         */
        public async authHandler(method: "GET" | "POST" | "PATCH" | "PUT" | "DELETE" | "HEAD" | "OPTIONS" | "TRACE", path: string[], body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/api/auth/${path.map(encodeURIComponent).join("/")}`, body, options)
        }

        /**
         * Returns a participant's public profile including team affiliations.
         */
        public async getUserProfile(id: string): Promise<UserProfile> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(id)}`)
            return await resp.json() as UserProfile
        }

        /**
         * Admin-only directory listing of every platform user. Gated to site
         * administrators so the admin panel is the single place to browse accounts.
         */
        public async listUsers(): Promise<{
    users: UserSummary[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/users`)
            return await resp.json() as {
    users: UserSummary[]
}
        }

        /**
         * Grants or revokes the global SITE_ADMIN role. Restricted to existing site
         * administrators, the single choke point that bootstraps platform-wide control.
         */
        public async setUserSiteRole(id: string, params: SetSiteRoleParams): Promise<UserProfile> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                siteRole: params.siteRole,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/users/${encodeURIComponent(id)}/site-role`, JSON.stringify(body), {headers})
            return await resp.json() as UserProfile
        }

        /**
         * Updates the authenticated user's own profile fields (issue #7). A user may
         * only edit their own record.
         */
        public async updateUserProfile(id: string, params: UpdateUserParams): Promise<UserProfile> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                biography:      params.biography,
                careerOverview: params.careerOverview,
                image:          params.image,
                name:           params.name,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/users/${encodeURIComponent(id)}`, JSON.stringify(body), {headers})
            return await resp.json() as UserProfile
        }
    }
}

export namespace eventmanager {
    export interface AddMemberParams {
        authorization: string
        userId: string
    }

    export interface AddScheduleParams {
        authorization: string
        title?: string | null
        startsAt: string
        endsAt?: string | null
        location?: string | null
    }

    export interface AssignRaceResultParams {
        authorization: string
        position?: number | null
        points: number
        gateNumber?: number | null
        finishTime?: string | null
        margin?: string | null
        passingOrder?: string | null
        final3F?: string | null
    }

    /**
     * API-facing skill class tier type. This is a plain string-literal union rather
     * than the Prisma-generated `ClassTier` enum: Encore's API schema parser cannot
     * use Prisma's runtime enum object as a type ("value used as type"). The values
     * are byte-for-byte identical to the Prisma enum, so they interoperate with the
     * database layer without conversion.
     */
    export type ClassTier = "PRE_OP" | "OP" | "G3" | "G2" | "G1"

    export interface ClassTierInfo {
        tier: ClassTier
        label: string
        rank: number
    }

    export interface CreateDatasetParams {
        authorization: string
        source: string
        rows?: number
    }

    export interface CreateEventParams {
        authorization: string
        name: string
        description?: string | null
        ownerType: EventOwnerType
        organizationId?: string | null
        ownerUserId?: string | null
        scoringType: ScoringType
        classRestriction?: ClassTier | null
    }

    export interface CreateRaceEventParams {
        authorization: string
        name: string
        sequence?: number
        distanceMeters: number
        trackType: string
        location: string
        scoringType?: number | null
        classRestriction?: ClassTier | null
        startsAt?: string | null
        endsAt?: string | null
    }

    /**
     * API-facing string union mirroring the Prisma DatasetStatus enum. Encore's
     * schema parser cannot use Prisma's runtime enum object as a type, so this is
     * declared as a plain literal union with byte-identical values.
     */
    export type DatasetStatus = "PENDING" | "RUNNING" | "DONE" | "FAILED"

    export interface DatasetView {
        id: string
        eventId: string
        source: string
        rows: number
        status: DatasetStatus
        importedAt: string | null
        createdAt: string
        updatedAt: string
    }

    export interface DeleteDatasetParams {
        authorization: string
    }

    export interface DeleteEventParams {
        authorization: string
    }

    export interface DeleteRaceEventParams {
        authorization: string
    }

    export interface DeleteRaceResultParams {
        authorization: string
    }

    export interface EligibleEvent {
        id: string
        name: string
        organizationId: string | null
        classRestriction: ClassTier | null
    }

    export interface EventDetail {
        id: string
        name: string
        description: string | null
        ownerType: EventOwnerType
        organizationId: string | null
        ownerUserId: string | null
        status: EventStatus
        scoringType: number
        scoringTypeLabel: string
        classRestriction: ClassTier | null
        raceEvents: RaceEventView[]
        members: EventMemberView[]
        schedules: EventScheduleView[]
        pointsOverview: PointsEntryView[] | null
        ladderOverview: LadderEntryView[] | null
        createdAt: string
        updatedAt: string
    }

    export interface EventMemberView {
        userId: string
        name: string
        classTier: ClassTier | null
    }

    /**
     * API-facing string unions mirroring the Prisma enums. Encore's schema parser
     * cannot use Prisma's runtime enum objects as types, so these are declared as
     * plain literal unions with byte-identical values (see classtier.ts).
     */
    export type EventOwnerType = "ORGANIZATION" | "USER"

    export interface EventScheduleView {
        id: string
        title: string | null
        startsAt: string
        endsAt: string | null
        location: string | null
    }

    export type EventStatus = "DRAFT" | "UNOFFICIAL" | "OFFICIAL" | "CONCLUDED"

    export interface LadderEntryView {
        userId: string
        name: string
        elo: number
        wins: number
        losses: number
        rank: number
    }

    export interface LadderMatchParams {
        authorization: string
        winnerId: string
        loserId: string
    }

    export interface ListEventsParams {
        organizationId?: string
        classRestriction?: ClassTier
    }

    export interface MergeRaceResultsParams {
        authorization: string
        results: RaceResultInput[]
    }

    export interface PointsEntryView {
        userId: string
        name: string
        points: number
    }

    /**
     * A RaceEvent is a single race contained within an Event. The parent Event acts
     * as the container/scoreboard; each RaceEvent carries its own distance, track
     * type (free-text) and location. Authorization for every mutation is delegated
     * to the parent event via requireEventPermission, so both organization-owned
     * and user-owned events (and site admins) are handled uniformly.
     */
    export interface RaceEventDetail {
        id: string
        eventId: string
        name: string
        sequence: number
        distanceMeters: number
        trackType: string
        location: string
        scoringType: number | null
        classRestriction: ClassTier | null
        startsAt: string | null
        endsAt: string | null
        createdAt: string
        updatedAt: string
    }

    export interface RaceEventView {
        id: string
        name: string
        sequence: number
        distanceMeters: number
        trackType: string
        location: string
        scoringType: number | null
        classRestriction: ClassTier | null
        startsAt: string | null
        endsAt: string | null
    }

    /**
     * One participant's entry in a bulk standings payload.
     */
    export interface RaceResultInput {
        userId: string
        position?: number | null
        points: number
        gateNumber?: number | null
        finishTime?: string | null
        margin?: string | null
        passingOrder?: string | null
        final3F?: string | null
    }

    /**
     * Per-race results. Event admins assign points to participants on a specific
     * RaceEvent; the event-level EventPointsEntry aggregate is then recomputed as
     * the sum of that participant's RaceResult.points across every race in the
     * event, keeping the existing points overview in sync.
     */
    export interface RaceResultView {
        id: string
        raceEventId: string
        userId: string
        position: number | null
        points: number
        gateNumber: number | null
        finishTime: string | null
        margin: string | null
        passingOrder: string | null
        final3F: string | null
        createdAt: string
        updatedAt: string
    }

    export interface RemoveMemberParams {
        authorization: string
    }

    export interface ReplaceRaceResultsParams {
        authorization: string
        results: RaceResultInput[]
    }

    export type ScoringType = 1 | 2

    export interface SetPointsParams {
        authorization: string
        points: number
    }

    export interface SetStatusParams {
        authorization: string
        status: EventStatus
    }

    export interface SetUserClassParams {
        authorization: string
        organizationId?: string | null
        classTier: ClassTier | null
    }

    export interface UpdateDatasetStatusParams {
        authorization: string
        status: DatasetStatus
    }

    export interface UpdateEventParams {
        authorization: string
        name?: string
        description?: string | null
        classRestriction?: ClassTier | null
    }

    export interface UpdateRaceEventParams {
        authorization: string
        name?: string
        sequence?: number
        distanceMeters?: number
        trackType?: string
        location?: string
        scoringType?: number | null
        classRestriction?: ClassTier | null
        startsAt?: string | null
        endsAt?: string | null
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addEventMember = this.addEventMember.bind(this)
            this.addEventSchedule = this.addEventSchedule.bind(this)
            this.assignRaceResult = this.assignRaceResult.bind(this)
            this.createDataset = this.createDataset.bind(this)
            this.createEvent = this.createEvent.bind(this)
            this.createRaceEvent = this.createRaceEvent.bind(this)
            this.deleteDataset = this.deleteDataset.bind(this)
            this.deleteEvent = this.deleteEvent.bind(this)
            this.deleteRaceEvent = this.deleteRaceEvent.bind(this)
            this.deleteRaceResult = this.deleteRaceResult.bind(this)
            this.getEvent = this.getEvent.bind(this)
            this.getRaceEvent = this.getRaceEvent.bind(this)
            this.listClassTiers = this.listClassTiers.bind(this)
            this.listDatasets = this.listDatasets.bind(this)
            this.listEligibleEvents = this.listEligibleEvents.bind(this)
            this.listEvents = this.listEvents.bind(this)
            this.listRaceEvents = this.listRaceEvents.bind(this)
            this.listRaceResults = this.listRaceResults.bind(this)
            this.mergeRaceResults = this.mergeRaceResults.bind(this)
            this.recordLadderMatch = this.recordLadderMatch.bind(this)
            this.removeEventMember = this.removeEventMember.bind(this)
            this.replaceRaceResults = this.replaceRaceResults.bind(this)
            this.setEventPoints = this.setEventPoints.bind(this)
            this.setEventStatus = this.setEventStatus.bind(this)
            this.setUserClass = this.setUserClass.bind(this)
            this.updateDatasetStatus = this.updateDatasetStatus.bind(this)
            this.updateEvent = this.updateEvent.bind(this)
            this.updateRaceEvent = this.updateRaceEvent.bind(this)
        }

        /**
         * Registers a participant for an event. Enforces the event's class restriction
         * (issue #3) and seeds the scoring record for the event's scoring type.
         */
        public async addEventMember(id: string, params: AddMemberParams): Promise<EventDetail> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                userId: params.userId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/events/${encodeURIComponent(id)}/members`, JSON.stringify(body), {headers})
            return await resp.json() as EventDetail
        }

        /**
         * Adds a schedule slot to an event (issue #4).
         */
        public async addEventSchedule(id: string, params: AddScheduleParams): Promise<EventDetail> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                endsAt:   params.endsAt,
                location: params.location,
                startsAt: params.startsAt,
                title:    params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/events/${encodeURIComponent(id)}/schedules`, JSON.stringify(body), {headers})
            return await resp.json() as EventDetail
        }

        /**
         * Assigns (or updates) a participant's result on a race. Gated by event-update
         * permission on the parent event (event admins, with site-admin override).
         */
        public async assignRaceResult(eventId: string, raceId: string, userId: string, params: AssignRaceResultParams): Promise<RaceResultView> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                final3F:      params.final3F,
                finishTime:   params.finishTime,
                gateNumber:   params.gateNumber,
                margin:       params.margin,
                passingOrder: params.passingOrder,
                points:       params.points,
                position:     params.position,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/events/${encodeURIComponent(eventId)}/races/${encodeURIComponent(raceId)}/results/${encodeURIComponent(userId)}`, JSON.stringify(body), {headers})
            return await resp.json() as RaceResultView
        }

        /**
         * Registers a new dataset import record against an event. The dataset starts in
         * the PENDING state; the actual ingest pipeline is not yet wired up, so this
         * only records the intent to import `source`.
         */
        public async createDataset(eventId: string, params: CreateDatasetParams): Promise<DatasetView> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                rows:   params.rows,
                source: params.source,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/events/${encodeURIComponent(eventId)}/datasets`, JSON.stringify(body), {headers})
            return await resp.json() as DatasetView
        }

        /**
         * Creates an event owned by either an organization or a single user (issue #4).
         * Org-owned events require event-create permission in the organization (or site
         * admin). User-owned events may be created by any authenticated user for
         * themselves; site admins may create one on behalf of any user.
         */
        public async createEvent(params: CreateEventParams): Promise<EventDetail> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                classRestriction: params.classRestriction,
                description:      params.description,
                name:             params.name,
                organizationId:   params.organizationId,
                ownerType:        params.ownerType,
                ownerUserId:      params.ownerUserId,
                scoringType:      params.scoringType,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/events`, JSON.stringify(body), {headers})
            return await resp.json() as EventDetail
        }

        /**
         * Adds a race to an event. Gated by event-update permission on the parent event.
         */
        public async createRaceEvent(eventId: string, params: CreateRaceEventParams): Promise<RaceEventDetail> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                classRestriction: params.classRestriction,
                distanceMeters:   params.distanceMeters,
                endsAt:           params.endsAt,
                location:         params.location,
                name:             params.name,
                scoringType:      params.scoringType,
                sequence:         params.sequence,
                startsAt:         params.startsAt,
                trackType:        params.trackType,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/events/${encodeURIComponent(eventId)}/races`, JSON.stringify(body), {headers})
            return await resp.json() as RaceEventDetail
        }

        /**
         * Deletes a dataset import record from an event.
         */
        public async deleteDataset(eventId: string, datasetId: string, params: DeleteDatasetParams): Promise<{
    deleted: boolean
}> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/events/${encodeURIComponent(eventId)}/datasets/${encodeURIComponent(datasetId)}`, undefined, {headers})
            return await resp.json() as {
    deleted: boolean
}
        }

        /**
         * Deletes an event and its related records.
         */
        public async deleteEvent(id: string, params: DeleteEventParams): Promise<{
    deleted: boolean
}> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/events/${encodeURIComponent(id)}`, undefined, {headers})
            return await resp.json() as {
    deleted: boolean
}
        }

        /**
         * Deletes a race and its results (cascade). Gated by event-delete permission.
         */
        public async deleteRaceEvent(eventId: string, raceId: string, params: DeleteRaceEventParams): Promise<{
    deleted: boolean
}> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/events/${encodeURIComponent(eventId)}/races/${encodeURIComponent(raceId)}`, undefined, {headers})
            return await resp.json() as {
    deleted: boolean
}
        }

        /**
         * Removes a single participant's result from a race and recomputes that
         * participant's event-level aggregate. Returns 404 if no such result exists.
         * Gated by event-update permission on the parent event.
         */
        public async deleteRaceResult(eventId: string, raceId: string, userId: string, params: DeleteRaceResultParams): Promise<{
    deleted: boolean
}> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/events/${encodeURIComponent(eventId)}/races/${encodeURIComponent(raceId)}/results/${encodeURIComponent(userId)}`, undefined, {headers})
            return await resp.json() as {
    deleted: boolean
}
        }

        /**
         * Returns a single event with members, schedules and the scoring overview that
         * matches its scoring type.
         */
        public async getEvent(id: string): Promise<EventDetail> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/events/${encodeURIComponent(id)}`)
            return await resp.json() as EventDetail
        }

        /**
         * Returns a single race within an event.
         */
        public async getRaceEvent(eventId: string, raceId: string): Promise<RaceEventDetail> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/events/${encodeURIComponent(eventId)}/races/${encodeURIComponent(raceId)}`)
            return await resp.json() as RaceEventDetail
        }

        /**
         * Lists the available skill class tiers (issue #3) ordered from lowest to
         * highest skill.
         */
        public async listClassTiers(): Promise<{
    tiers: ClassTierInfo[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/classes`)
            return await resp.json() as {
    tiers: ClassTierInfo[]
}
        }

        /**
         * Lists the dataset import records scoped to a single event, newest first.
         */
        public async listDatasets(eventId: string): Promise<{
    datasets: DatasetView[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/events/${encodeURIComponent(eventId)}/datasets`)
            return await resp.json() as {
    datasets: DatasetView[]
}
        }

        /**
         * Returns the events a participant is eligible to enter based on their class
         * tier and each event's class restriction (issue #3).
         */
        public async listEligibleEvents(userId: string): Promise<{
    events: EligibleEvent[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(userId)}/eligible-events`)
            return await resp.json() as {
    events: EligibleEvent[]
}
        }

        /**
         * Lists events, optionally filtered by organization or class restriction.
         */
        public async listEvents(params: ListEventsParams): Promise<{
    events: EventDetail[]
}> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                classRestriction: params.classRestriction === undefined ? undefined : String(params.classRestriction),
                organizationId:   params.organizationId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/events`, undefined, {query})
            return await resp.json() as {
    events: EventDetail[]
}
        }

        /**
         * Lists the races within an event, ordered by their sequence.
         */
        public async listRaceEvents(eventId: string): Promise<{
    races: RaceEventDetail[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/events/${encodeURIComponent(eventId)}/races`)
            return await resp.json() as {
    races: RaceEventDetail[]
}
        }

        /**
         * Lists the results recorded for a single race, ordered by finishing position.
         */
        public async listRaceResults(eventId: string, raceId: string): Promise<{
    results: RaceResultView[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/events/${encodeURIComponent(eventId)}/races/${encodeURIComponent(raceId)}/results`)
            return await resp.json() as {
    results: RaceResultView[]
}
        }

        /**
         * Merge/upsert bulk standings: each participant in the payload is upserted, but
         * results for users absent from the payload are left untouched (no deletion).
         * Only the participants named in the payload have their event-level aggregate
         * recomputed. Same gating/validation as the full-replace endpoint.
         * POST (rather than PATCH) is used here to match the codebase's convention of
         * POSTing to a collection path for additive mutations (see addEventMember on
         * /events/:id/members and recordLadderMatch on /events/:id/ladder/matches),
         * keeping the full-replace semantics on PUT and the additive merge on POST.
         */
        public async mergeRaceResults(eventId: string, raceId: string, params: MergeRaceResultsParams): Promise<{
    results: RaceResultView[]
}> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                results: params.results,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/events/${encodeURIComponent(eventId)}/races/${encodeURIComponent(raceId)}/results`, JSON.stringify(body), {headers})
            return await resp.json() as {
    results: RaceResultView[]
}
        }

        /**
         * Records a 1v1 result on a ladder-elo event and updates both ratings
         * (ladder overview).
         */
        public async recordLadderMatch(id: string, params: LadderMatchParams): Promise<EventDetail> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                loserId:  params.loserId,
                winnerId: params.winnerId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/events/${encodeURIComponent(id)}/ladder/matches`, JSON.stringify(body), {headers})
            return await resp.json() as EventDetail
        }

        /**
         * Removes a participant from an event.
         */
        public async removeEventMember(id: string, userId: string, params: RemoveMemberParams): Promise<EventDetail> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/events/${encodeURIComponent(id)}/members/${encodeURIComponent(userId)}`, undefined, {headers})
            return await resp.json() as EventDetail
        }

        /**
         * Full-replace bulk standings: the payload becomes the complete set of results
         * for the race. Each participant is upserted; any existing result for a user not
         * present in the payload is deleted. Every affected participant's event-level
         * aggregate (added, changed and removed) is recomputed. Gated by event-update
         * permission on the parent event.
         */
        public async replaceRaceResults(eventId: string, raceId: string, params: ReplaceRaceResultsParams): Promise<{
    results: RaceResultView[]
}> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                results: params.results,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/events/${encodeURIComponent(eventId)}/races/${encodeURIComponent(raceId)}/results`, JSON.stringify(body), {headers})
            return await resp.json() as {
    results: RaceResultView[]
}
        }

        /**
         * Sets a participant's points on a points-based event (points overview).
         */
        public async setEventPoints(id: string, userId: string, params: SetPointsParams): Promise<EventDetail> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                points: params.points,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/events/${encodeURIComponent(id)}/points/${encodeURIComponent(userId)}`, JSON.stringify(body), {headers})
            return await resp.json() as EventDetail
        }

        /**
         * Sets an event's lifecycle status. Endorsing an event as OFFICIAL is a
         * platform action reserved for site administrators; all other statuses
         * (DRAFT/UNOFFICIAL/CONCLUDED) may be set by anyone who can update the event.
         */
        public async setEventStatus(id: string, params: SetStatusParams): Promise<EventDetail> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                status: params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/events/${encodeURIComponent(id)}/status`, JSON.stringify(body), {headers})
            return await resp.json() as EventDetail
        }

        /**
         * Tags a participant with a skill class tier (issue #3). This is an
         * administrative action: within an organization it is gated by the same RBAC
         * role that manages events; site administrators may set a class tier globally
         * (no organization context required).
         */
        public async setUserClass(userId: string, params: SetUserClassParams): Promise<{
    userId: string
    classTier: ClassTier | null
}> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                classTier:      params.classTier,
                organizationId: params.organizationId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/users/${encodeURIComponent(userId)}/class`, JSON.stringify(body), {headers})
            return await resp.json() as {
    userId: string
    classTier: ClassTier | null
}
        }

        /**
         * Mutates a dataset's ingest status (e.g. PENDING -> RUNNING -> DONE/FAILED).
         * Transitioning to DONE stamps `importedAt`; clearing it resets the timestamp.
         */
        public async updateDatasetStatus(eventId: string, datasetId: string, params: UpdateDatasetStatusParams): Promise<DatasetView> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                status: params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/events/${encodeURIComponent(eventId)}/datasets/${encodeURIComponent(datasetId)}/status`, JSON.stringify(body), {headers})
            return await resp.json() as DatasetView
        }

        /**
         * Updates an event's editable fields (scoring type is immutable once set).
         */
        public async updateEvent(id: string, params: UpdateEventParams): Promise<EventDetail> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                classRestriction: params.classRestriction,
                description:      params.description,
                name:             params.name,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/events/${encodeURIComponent(id)}`, JSON.stringify(body), {headers})
            return await resp.json() as EventDetail
        }

        /**
         * Updates a race's editable fields. Gated by event-update permission.
         */
        public async updateRaceEvent(eventId: string, raceId: string, params: UpdateRaceEventParams): Promise<RaceEventDetail> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                classRestriction: params.classRestriction,
                distanceMeters:   params.distanceMeters,
                endsAt:           params.endsAt,
                location:         params.location,
                name:             params.name,
                scoringType:      params.scoringType,
                sequence:         params.sequence,
                startsAt:         params.startsAt,
                trackType:        params.trackType,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/events/${encodeURIComponent(eventId)}/races/${encodeURIComponent(raceId)}`, JSON.stringify(body), {headers})
            return await resp.json() as RaceEventDetail
        }
    }
}

/**
 * Encore will consider this directory and all its subdirectories as part of the "frontend" service.
 * https://encore.dev/docs/ts/primitives/services
 */
export namespace frontend {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.assets = this.assets.bind(this)
        }

        /**
         * Serve static files from the ./dist directory
         */
        public async assets(path: string[]): Promise<void> {
            await this.baseClient.callTypedAPI("HEAD", `/${path.map(encodeURIComponent).join("/")}`)
        }
    }
}

/**
 * hello service responds to requests with a personalized greeting.
 */
export namespace hello {
    export interface Response {
        message: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.get = this.get.bind(this)
            this.index = this.index.bind(this)
        }

        /**
         * Returns a personalized greeting.
         */
        public async get(name: string): Promise<Response> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/hello/${encodeURIComponent(name)}`)
            return await resp.json() as Response
        }

        /**
         * Landing page with usage instructions.
         */
        public async index(method: "GET", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/`, body, options)
        }
    }
}

export namespace teammanager {
    export interface Team {
        id: string
        name: string
        slug: string
        logo: string | null
        stats: TeamStats
        administratorSlotsRemaining: number
        members: TeamMemberSummary[]
    }

    export interface TeamMemberSummary {
        userId: string
        name: string
        role: string
    }

    /**
     * A team is modelled as a better-auth organization (issue #6). Beyond the core
     * organization fields it carries a set of aggregate "container" statistics that
     * higher-level ranking features can populate.
     */
    export interface TeamStats {
        rankingAverage: number | null
        pointsAverage: number | null
        seasonRank: number | null
        averagePointsPerEvent: number | null
    }

    export interface UpdateTeamStatsParams {
        authorization: string
        rankingAverage?: number | null
        pointsAverage?: number | null
        seasonRank?: number | null
        averagePointsPerEvent?: number | null
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getTeam = this.getTeam.bind(this)
            this.updateTeamStats = this.updateTeamStats.bind(this)
        }

        /**
         * Returns a team with its members and aggregate statistics.
         */
        public async getTeam(id: string): Promise<Team> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/teams/${encodeURIComponent(id)}`)
            return await resp.json() as Team
        }

        /**
         * Updates a team's aggregate statistics. Requires a role with organization
         * update permission (administrator) in the target team.
         */
        public async updateTeamStats(id: string, params: UpdateTeamStatsParams): Promise<Team> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                averagePointsPerEvent: params.averagePointsPerEvent,
                pointsAverage:         params.pointsAverage,
                rankingAverage:        params.rankingAverage,
                seasonRank:            params.seasonRank,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/teams/${encodeURIComponent(id)}/stats`, JSON.stringify(body), {headers})
            return await resp.json() as Team
        }
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | auth.AuthParams
  | Promise<auth.AuthParams | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "hzvac-Generated-TS-Client (Encore/v1.57.9)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: auth.AuthParams | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
